version: '2'
services:
  nodeschool:
    build: .
    volumes:
      - ./projects:/home/nodeschool/projects
    tty: true
    stdin_open: true
    command: "/bin/bash"
    ports: 
      - "3000:3000"
